name: CI
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - run: |
          curl -L -u "github-auth:${GITHUB_TOKEN}" charts.nodis.com.br 2> /dev/null
          echo "#####################################"
          curl -H "Authorization: token ${GITHUB_TOKEN}" https://api.github.com/repos/nodis-com-br/github-auth 2> /dev/null | jq -r

      
